services:

  db:
    environment:
      MYSQL_ROOT_HOST: ${DB_ROOT_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./ddl:/ddl
      - ./.db/my.cnf:/etc/mysql/my.cnf
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  db_data: